### ISSUE TITLE
[connect > portal] - Required Features

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1181]
Connect feature list needed from Portal

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1163
- [ ] https://github.com/wormhole-foundation/wormhole-connect/pull/1174
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1182
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1183
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1221
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1226
```
