### ISSUE TITLE
[Bug] <Ticket 12745 OSMO -> AVAX Bridge transaction not found, check that you have the correct chain and transaction ID> 

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### have you checked our wiki for common solutions?

- [X] I have searched the wiki or docs

### Bridge Experience

https://portalbridge.com

### Operation Details

```markdown
- Source Chain: OSMO
- Source Chain Wallet: osmo1v9ls8y0ue53cx49ukn9cnusezv55qh2s4l7xtl
- Target Chain: AVAX
- Target Chain Wallet: 0x005abc15330c2ea8ea899d454b6695b4ea3cf348
- Asset Type: USDC
- Tx: 1e7f80c8f8a6c2189907af27e4dbf0aff258d7aebc35d492da157d0a6cf7aab2
- Gateway Tx: 742a30905485c402fbae5c85eacfd2206bb869fe1ae83e75f92b2c1971c29958
https://wormholescan.io/#/tx/1e7f80c8f8a6c2189907af27e4dbf0aff258d7aebc35d492da157d0a6cf7aab2
```

### Current Behavior

Bridge transaction not found, check that you have the correct chain and transaction ID

### Expected Behavior

Able to resume and complete the TX

### Steps To Reproduce

1. https://portalbridge.com/
2. select OSMO as source chain
3. tried to resume with both TXID 1e7f80c8f8a6c2189907af27e4dbf0aff258d7aebc35d492da157d0a6cf7aab2 and 742a30905485c402fbae5c85eacfd2206bb869fe1ae83e75f92b2c1971c29958 in wormholescan with same result

```[tasklist]
### Tasks
- [ ] https://github.com/XLabs/portal-bridge-ui/issues/606
```
