### ISSUE TITLE
Wormhole Connect v0.1.7

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1364]
Task tracker for the next release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1299
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1305
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1288
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/664
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1365
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1379
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1374
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1387
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1389
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.1.7
