### ISSUE TITLE
Wormhole Connect v0.2.0 (ETH bridge, tBTC fixes, Vite tooling, small UI changes)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1375]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1415
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1402
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1394
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1429
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1248
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1422
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/952
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1390
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1461
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.0
