### ISSUE TITLE
Wormhole Connect v0.2.1 (ETH bridge refinement, bugfixes)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1416]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1474
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1481
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1459
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1470
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.1
