### ISSUE TITLE
Wormhole Connect v0.2.2

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1437]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1472
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1344
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1471
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1487
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1488
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1392
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1516
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1345
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1533
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1534
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1529
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1537
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1509
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1569
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1570
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.2
