### ISSUE TITLE
Wormhole Connect v0.2.3

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1475]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1296
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1497
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1579
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1436
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1607
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1608
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1614
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1621
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.3
