### ISSUE TITLE
Wormhole Connect v0.2.4

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1496]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1624
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1625
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1458
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1654
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1658
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.4
