### ISSUE TITLE
Wormhole Connect v0.2.5

### ISSUE THREAD

**Issue by tonyjin** [wormhole-foundation/wormhole-connect#1647]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1343
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1500
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1287
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1663
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1659
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1703
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1691
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.5
