### ISSUE TITLE
Wormhole Connect v0.2.6 (Cosmos hotfix)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1655]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1670
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1749
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1504
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1681
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/698
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.6
