### ISSUE TITLE
[task] - remove BONK from built in tokens

### ISSUE THREAD

**Issue by sebastianscatularo** [wormhole-foundation/wormhole-connect#1703]
### Tasks
- [x] Remove BONK asset from [tokens.ts](https://github.com/wormhole-foundation/wormhole-connect/blob/development/wormhole-connect/src/config/mainnet/tokens.ts#L2503)
- [x] Add configuration at portal bridge to support it

### Related to
- [x] https://github.com/XLabs/portal-bridge-ui/issues/742

### Acceptance Criteria

Given an user, when I use **netlify** prod or preview version of Wormhole Connect
Then I'm not able to see BONK asset 
since it is not longer part of built in token
