### ISSUE TITLE
Wormhole Connect v0.2.7 (Injective support, Solana prio fee)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1716]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1697
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1763
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1641
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1776
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.2.7
