### ISSUE TITLE
Wormhole Connect v0.3.0 (Direct import)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1721]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1715
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1261
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1808
```

**Comment by aadam-10** [comment]
https://www.npmjs.com/package/@wormhole-foundation/wormhole-connect/v/0.3.0
