### ISSUE TITLE
Wormhole Connect v0.3.4

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#1835]
Task tracker for a future release. The contents are informational only and the final release candidate may contain different changes than what's outlined below.

```[tasklist]
### Task list
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1801
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1720
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1774
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1738
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1710
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/932
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1892
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1895
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/1800
```
