### ISSUE TITLE
Beta M1 - Soft beta launch

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#234]
This tasklist is for collecting tasks necessary for the first public rollout (minimum viable product).

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/254
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/223
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/219
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/164
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/163
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/134
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/272
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/278
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/255
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/218
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/126
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/166
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/181
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/345
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/395
```
