### ISSUE TITLE
General availability M1 - Extension with Sui, Misc improvements

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#238]
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/307
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/306
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/111
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/329
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/348
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/347
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/344
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/341
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/339
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/342
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/361
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/362
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/373
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/354
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/333
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/331
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/397
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/338
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/400
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/386
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/410
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/394
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/436
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/430
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/431
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/429
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/454
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/548
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/580
```
