### ISSUE TITLE
In-progress widget release

### ISSUE THREAD

**Issue by Wesleyleung** [wormhole-foundation/wormhole-connect#2801]
Tracks all the tickets that need to be completed for in-progress widget

```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2773
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2759
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2760
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2781
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2796
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2810
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2809
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2807
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2804
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2885
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2892
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2894
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2902
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2903
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2904
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/2930
```
```[tasklist]
### Tasks
```

**Comment by Wesleyleung** [comment]
Consolidated tickets to finish the widget. These are all P2 priority in the absolute sense, but in the task list above they are ordered in relative priority to each other.

**Comment by tsadovska** [comment]
Issues found while checking tasks:
* #2885 
* #2892
* #2894
* #2902 
* #2903 
* #2904
