### ISSUE TITLE
General availability M2 - Aptos (no gas dropoff)

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#349]
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/602
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/372
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/433
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/505
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/579
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/496
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/531
```
