### ISSUE TITLE
General availability M2.5 - Sei support

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#599]
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/603
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/658
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/659
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/683
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/560
```
