### ISSUE TITLE
General availability M3 - Hashflow routing

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#677]
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/676
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/600
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/615
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/616
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/617
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/621
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/622
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/623
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/624
- [ ] https://github.com/wormhole-foundation/wormhole-connect/issues/625
```

**Comment by aadam-10** [comment]
this is tracked elsewhere now
