### ISSUE TITLE
General availability M4 - Cosmos chains via WH Gateway

### ISSUE THREAD

**Issue by aadam-10** [wormhole-foundation/wormhole-connect#761]
```[tasklist]
### Tasks
- [x] External Chain -> Cosmos Chain
- [x] Cosmos Chain -> External Chain
- [x] Cosmos Chain -> Cosmos Chain
- [x] Support for other Cosmos tokens/networks other than Sei
- [x] Look into any missing wallet integrations for the new added networks
- [x] Changes to the UI to reflect the route the transfer will take
```
